package paltonmorgans;

import com.fazecast.jSerialComm.SerialPort;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.InputStream;
import java.net.URL;
import paltonmorgans.Departments;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javaswingdev.drawer.Drawer;
import javaswingdev.drawer.DrawerController;
import javaswingdev.drawer.DrawerItem;
import javaswingdev.drawer.EventDrawer;
import javax.swing.ImageIcon;
//import javax.swing.ImageIcon;

import javax.swing.JComboBox;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import paltonmorgans.Departments;
import paltonmorgans.Login;
import paltonmorgans.Staff;

/**
 *
 * @author USER
 */
public class AssetManage extends javax.swing.JFrame {

    private JTextField AssetCode;
    private StringBuilder barcode = new StringBuilder();
    private Timer timer;
 private DrawerController drawer;
    /**
     * Creates new form AssetManage
     */
 
    public AssetManage() {

        initComponents();
    drawer = Drawer.newDrawer(this)
                .background(new Color(90, 90, 90))
                .closeOnPress(true)
                .backgroundTransparent(0.3f)
                .leftDrawer(true)
                .enableScroll(true)
                .enableScrollUI(false)
                .headerHeight(160)
           //  .header(new Header())
               .space(3)
                .addChild(new DrawerItem("User ").icon(new ImageIcon(getClass().getResource("/icon/user.png"))).build())
                .addChild(new DrawerItem("Contacts").icon(new ImageIcon(getClass().getResource("/icon/cont.png"))).build())
                .addChild(new DrawerItem("Report").icon(new ImageIcon(getClass().getResource("/icon/report.png"))).build())
                .addChild(new DrawerItem("Income").icon(new ImageIcon(getClass().getResource("/icon/income.png"))).build())
                .addChild(new DrawerItem("Expense").icon(new ImageIcon(getClass().getResource("/icon/expense.png"))).build())
                .addChild(new DrawerItem("Datas").icon(new ImageIcon(getClass().getResource("/icon/data.png"))).build())
                .addFooter(new DrawerItem("Exit").icon(new ImageIcon(getClass().getResource("/icon/exit.png"))).build())
                .event(new EventDrawer() {
                    @Override
                    public void selected(int index, DrawerItem item) {
                     if(drawer.isShow()){
                         drawer.hide();
                     }
                    }
                })
                .build();
        fetchAssetList();
        GetCat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SerialNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AssetDesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Model = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Accessories = new javax.swing.JComboBox<>();
        UpdateBtn = new javax.swing.JButton();
        FifterBtn = new javax.swing.JButton();
        CleanBtn = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();
        TableTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssetTable = new javax.swing.JTable();
        AssetClass = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Floor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Building = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ReconciliationRemark = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        AssetCode1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AssetStatus1 = new javax.swing.JComboBox<>();
        Department = new javax.swing.JComboBox<>();
        Departments = new javax.swing.JComboBox<>();
        Location = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/myfistproject/icon/2.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1478, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("MANAGE ASSET");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 144, 35));

        sn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 244, 27));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("SerialNo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 73, 28));

        SerialNo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(SerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 244, 27));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("S/N");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 73, 28));

        AssetDesc.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(AssetDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 244, 27));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("AssetDesc");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 76, 28));

        Model.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(Model, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 244, 27));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Model");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 76, 28));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("AssetStatus");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 35));

        Accessories.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Accessories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FURNITURE AND FITTINGS", "OFFICE EQUIPMENT", "COMPUTER EQUIPMENT", "MOTOR VEHICLE", "MACHINE AND PLANT", " " }));
        Accessories.setBorder(null);
        jPanel2.add(Accessories, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 88, 241, 29));

        UpdateBtn.setBackground(new java.awt.Color(255, 153, 0));
        UpdateBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        UpdateBtn.setText("Edit");
        UpdateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBtnMouseClicked(evt);
            }
        });
        jPanel2.add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 90, 33));

        FifterBtn.setBackground(new java.awt.Color(255, 153, 0));
        FifterBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        FifterBtn.setText("Filter");
        jPanel2.add(FifterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 90, 33));

        CleanBtn.setBackground(new java.awt.Color(255, 153, 0));
        CleanBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CleanBtn.setText("Clear");
        jPanel2.add(CleanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 330, 90, 33));

        AddBtn.setBackground(new java.awt.Color(255, 153, 0));
        AddBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        AddBtn.setText("Add");
        jPanel2.add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 90, 33));

        TableTitle.setBackground(new java.awt.Color(255, 255, 255));
        TableTitle.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        TableTitle.setText("MAGODO ASSET LIST");
        jPanel2.add(TableTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 368, 383, 35));

        AssetTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AssetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "S/N", "AssetCode", "AssetDesc", "AssetClass", "SerialNo", "Model", "Username", "Asset Status", "Department", "Location", "Floor", "Building", "RECONCILIATION REMARK "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AssetTable.setSelectionBackground(new java.awt.Color(255, 153, 0));
        AssetTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssetTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AssetTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1420, 303));

        AssetClass.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(AssetClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 244, 27));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("AssetClass");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 76, 28));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Location");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 76, 28));

        Username.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel2.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 244, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("Username");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 73, 28));

        Floor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(Floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 230, 244, 27));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setText("Department");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 89, 28));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Floor");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 76, 28));

        Building.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(Building, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 244, 27));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setText("Building");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 76, 28));

        ReconciliationRemark.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(ReconciliationRemark, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 280, 244, 27));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setText("ReconciliationRemark");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, -1, 28));

        AssetCode1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(AssetCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 244, 27));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("AssetCode");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 90, 28));

        AssetStatus1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AssetStatus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select you Item", "Good", "Bad", "Disposed" }));
        jPanel2.add(AssetStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 241, 29));

        Department.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Department" }));
        jPanel2.add(Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 241, 29));

        Departments.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Departments.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item Location" }));
        jPanel2.add(Departments, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 190, 241, 29));

        Location.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 244, 27));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("|||");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jDesktopPane1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new Staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void AssetTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssetTableMouseClicked
String originalAssetCode = ""; // Class-level variable

    DefaultTableModel model = (DefaultTableModel) AssetTable.getModel();
    int Myindex = AssetTable.getSelectedRow();

    // Set form fields
    AssetCode1.setText(model.getValueAt(Myindex, 0).toString());         // asset_code
    AssetDesc.setText(model.getValueAt(Myindex, 1).toString());
    AssetClass.setText(model.getValueAt(Myindex, 2).toString());
    SerialNo.setText(model.getValueAt(Myindex, 3).toString());
    Model.setText(model.getValueAt(Myindex, 4).toString());
    Username.setText(model.getValueAt(Myindex, 5).toString());
    AssetStatus1.setSelectedItem(model.getValueAt(Myindex, 6).toString());
    Department.setSelectedItem(model.getValueAt(Myindex, 7).toString());
    Location.setText(model.getValueAt(Myindex, 8).toString());
    Floor.setText(model.getValueAt(Myindex, 9).toString());
    Building.setText(model.getValueAt(Myindex, 10).toString());
    ReconciliationRemark.setText(model.getValueAt(Myindex, 11).toString());

    // Save original asset_code for the update WHERE clause
    originalAssetCode = model.getValueAt(Myindex, 0).toString();

        // TODO add your handling code here:
    }//GEN-LAST:event_AssetTableMouseClicked
private void openInternalFrame(JInternalFrame frame) {
    jDesktopPane1.removeAll();              // clear previous contents
    jDesktopPane1.add(frame);               // add the new frame
    frame.setVisible(true);
    frame.setSize(jDesktopPane1.getSize()); // optional: make it fullscreen inside desktop
    frame.setLocation(0, 0);
    try {
        frame.setSelected(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }
}
    private void UpdateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBtnMouseClicked
// Assume originalAssetCode is stored when user selects the row
String originalAssetCode = AssetCode1.getText(); // or a separate variable if asset_code can change

if (sn.getText().isEmpty() || AssetDesc.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Missing Required Information");
} else {
    try {
        con = DriverManager.getConnection(localhost, username, password);

        String query = "UPDATE public.magodoffit SET asset_code=?, asset_description=?, asset_class=?, serial_no=?, model=?, user_name=?, asset_status=?, department=?, location=?, floor=?, building=?, reconciliation_remark=? WHERE asset_code=?";
        PreparedStatement pst = con.prepareStatement(query);

        pst.setString(1, AssetCode1.getText()); // new asset code
        pst.setString(2, AssetDesc.getText());
        pst.setString(3, AssetClass.getText());
        pst.setString(4, SerialNo.getText());
        pst.setString(5, Model.getText());
        pst.setString(6, Username.getText());
        pst.setString(7, AssetStatus1.getSelectedItem() != null ? AssetStatus1.getSelectedItem().toString() : "");
        pst.setString(8, Department.getSelectedItem()!= null ? Department.getSelectedItem().toString() : "");
        pst.setString(9, Location.getText());
        pst.setString(10, Floor.getText());
        pst.setString(11, Building.getText());
        pst.setString(12, ReconciliationRemark.getText());

        pst.setString(13, originalAssetCode); // use old asset_code in WHERE clause

        int rowsAffected = pst.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Asset updated successfully!");
            fetchAssetList(); // refresh table
        } else {
            JOptionPane.showMessageDialog(this, "Asset not found or update failed.");
        }

        con.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error occurred: " + e.getMessage());
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBtnMouseClicked
    private void GetCat() {
        try {
            con = DriverManager.getConnection(localhost, username, password);
            St = con.createStatement();
            String query = "Select * FROM public.departments";
            Rs = St.executeQuery(query);
            while (Rs.next()) {
                String Mycat = Rs.getString("NAME");
                Department.addItem(Mycat);
                Departments.addItem(Mycat);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void readBarcodeFromSerial() {
        SerialPort[] ports = SerialPort.getCommPorts();

        if (ports.length == 0) {
            JOptionPane.showMessageDialog(this, "No serial ports detected!");
            return;
        }

        // Print available ports
        for (SerialPort p : ports) {
            System.out.println("Available port: " + p.getSystemPortName());
        }

        SerialPort port = ports[0]; // You can update this to a specific COM port
        port.setBaudRate(9600);

        if (port.openPort()) {
            JOptionPane.showMessageDialog(this, "Connected to " + port.getSystemPortName());

            new Thread(() -> {
                try (InputStream in = port.getInputStream()) {
                    StringBuilder buffer = new StringBuilder();
                    int data;
                    while ((data = in.read()) != -1) {
                        if (data == '\n' || data == '\r') {
                            if (buffer.length() > 0) {
                                final String result = buffer.toString().trim().replace('#', '/').toUpperCase();

                                SwingUtilities.invokeLater(() -> {
                                    AssetCode1.setText(result);
                                    fetchAssetByBarcode(result);
                                });
                                SwingUtilities.invokeLater(() -> AssetCode1.requestFocusInWindow());

                                buffer.setLength(0);
                            }
                        } else {
                            buffer.append((char) data);
                        }
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error reading from serial port:\n" + ex.getMessage());
                } finally {
                    port.closePort();
                }
            }).start();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to open port!");
        }
    }

    String localhost = "jdbc:postgresql://dpg-d1t09bjipnbc7380ert0-a.oregon-postgres.render.com/pms_vel1";
    String username = "pms_vel1_user";
    String password = "IJuc6JpYRt8joqbzXYMe74uEAQtTIjzC";

//String[] AssetStatus = {"Item 1", "Item 2", "Item 3"};

    private String getStringValue(Object value) {
        return value != null ? value.toString() : "";
    }
    private void searchBarcode() {
        String barcode = AssetCode1.getText().trim().toUpperCase();

        sn.setText(barcode);
        if (!barcode.isEmpty()) {
            fetchAssetByBarcode(barcode);
        }
    }
    Connection con = null;
    Statement St = null;
    ResultSet Rs = null;

    public void fetchAssetList() {
        String selectedDept = Department.getSelectedItem().toString();
        String selectedAccessories = Accessories.getSelectedItem().toString();

        try {
            con = DriverManager.getConnection(localhost, username, password);
            St = con.createStatement();

            if (selectedAccessories.equals("FURNITURE AND FITTINGS")) {
                Rs = St.executeQuery("SELECT * FROM public.VIFAF ORDER BY id ASC");
                 TableTitle.setText("VI FURNITURE AND FITTINGS LIST");
            } else if (selectedAccessories.equals("OFFICE EQUIPMENT")) {
                TableTitle.setText("VI OFFICE EQUIPMENT LIST");
                Rs = St.executeQuery("SELECT * FROM public.VICEQ ORDER BY id ASC");
            } else if (selectedAccessories.equals("MOTOR VEHICLE")) {
                TableTitle.setText("VI OFFICE FURNISHINGS LIST");
                Rs = St.executeQuery("SELECT * FROM public.VIMAV ORDER BY id ASC");
            } else if (selectedAccessories.equals("COMPUTER EQUIPMENT")) {
                TableTitle.setText("VI COMPUTER EQUIPMENT LIST");
                Rs = St.executeQuery("SELECT * FROM public.VICEQ ORDER BY id ASC");
            } else {
                TableTitle.setText("VI MACHINE AND PLATING LIST");
                Rs = St.executeQuery("SELECT * FROM public.VIMP ORDER BY id ASC");
            }

            AssetTable.setModel(DbUtils.resultSetToTableModel(Rs));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    public void fetchAssetData() {
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            con = DriverManager.getConnection(localhost, username, password);
            String asset_code = sn.getText();

            String query = "SELECT * FROM public.VIFAF WHERE asset_code = ?";
            pst = con.prepareStatement(query);
            pst.setString(1, asset_code); // Use setInt(1, ...) if asset_code is a number

            rs = pst.executeQuery();

            AssetTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pst != null) {
                    pst.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    private void fetchAssetByBarcode(String barcode) {
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        // List of views to search
        String[] views = {
            "public.VIFAF",
            "public.VICEQ",
            "public.VIMAV",
            "public.VIMP",
            "public.VIOFEQ"
        };

        try {
            conn = DriverManager.getConnection(localhost, username, password);

            boolean assetFound = false;

            for (String view : views) {
                String sql = "SELECT * FROM " + view + " WHERE asset_code = ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, barcode);
                rs = pst.executeQuery();

                if (rs.isBeforeFirst()) { // Data found
                    AssetTable.setModel(DbUtils.resultSetToTableModel(rs));
                    sn.setText("");
                    assetFound = true;
                    break;
                }
                // Close previous ResultSet before next query
                rs.close();
                pst.close();
            }

            if (!assetFound) {
                JOptionPane.showMessageDialog(this, "No asset found for barcode: " + barcode);
                AssetCode1.setText("");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error fetching asset: " + ex.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception e) {
            }
            try {
                if (pst != null) {
                    pst.close();
                }
            } catch (Exception e) {
            }
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception e) {
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssetManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssetManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssetManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssetManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssetManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Accessories;
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField AssetClass;
    private javax.swing.JTextField AssetCode1;
    private javax.swing.JTextField AssetDesc;
    private javax.swing.JComboBox<String> AssetStatus1;
    private javax.swing.JTable AssetTable;
    private javax.swing.JTextField Building;
    private javax.swing.JButton CleanBtn;
    private javax.swing.JComboBox<String> Department;
    private javax.swing.JComboBox<String> Departments;
    private javax.swing.JButton FifterBtn;
    private javax.swing.JTextField Floor;
    private javax.swing.JTextField Location;
    private javax.swing.JTextField Model;
    private javax.swing.JTextField ReconciliationRemark;
    private javax.swing.JTextField SerialNo;
    private javax.swing.JLabel TableTitle;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTextField Username;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField sn;
    // End of variables declaration//GEN-END:variables
}
